name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r rule_extractor/requirements.txt -r requirements-dev.txt
      - name: Lint
        run: |
          python -m ruff check rule_extractor
          python -m black --check rule_extractor
      - name: Tests
        env:
          OPENAI_API_KEY: dummy
        run: |
          pytest -q
